version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./volumes/data:/var/lib/kafka/data
      - ./volumes/logs:/var/lib/kafka/logs
    extra_hosts:
      - "kafka:10.0.2.15"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    labels:
      - "com.example.service=kafka"
    network_mode: "host"


  jmx-exporter:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "9309:9309" # modificare
    volumes:
      - ./jmx-exporter-config.yml:/etc/jmx_exporter/config.yml:ro
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9308"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    labels:
      - "com.example.service=jmx-exporter"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./volumes/logs:/var/lib/kafka/logs:ro
    command: filebeat -e -strict.perms=false
    healthcheck:
      test: ["CMD-SHELL", "filebeat test config"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    labels:
      - "com.example.service=filebeat"
    

secrets:
  kafka_secrets:
    file: ./kafka_secrets.yml