# Otel Collector for Kafka and Zookeeper
receivers:
  # Kafka receiver
  kafka:
    protocol_version: 2.0.0
    brokers:
      - kafka-broker:9092
    topic: your_specific_topic
    encoding: otlp_proto

  # Zookeeper receivers
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Zookeeper log collection
  filelog:
    include: [ /var/lib/zookeeper/log/*.log ]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?P<level>\w+)\s+(?P<message>.*)'
        timestamp:
          parse_from: timestamp
          layout: '%Y-%m-%d %H:%M:%S,%f'

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: logstash:5044
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [kafka, otlp]
      processors: [batch]
      exporters: [otlp, logging]
    logs:
      receivers: [kafka, otlp, filelog]
      processors: [batch]
      exporters: [otlp, logging]