version: '3'
services:
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "your-root-token-here"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data

  elk:
    image: sebp/elk:latest
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - elk_data:/var/lib/elasticsearch

volumes:
  vault_data:
  elk_data: